---
# External Ansible Galaxy roles (if needed)
roles:
  # - name: geerlingguy.docker
  #   version: 6.1.0
  # - name: community.postgresql
  #   version: 2.4.0

collections:
  - name: ansible.posix
    version: ">=1.5.0"
  - name: community.general
    version: ">=6.0.0"
