---
all:
  children:
    webservers:
      hosts:
        web01.example.com:
          ansible_host: 192.168.1.10
        web02.example.com:
          ansible_host: 192.168.1.11
    
    databases:
      hosts:
        db01.example.com:
          ansible_host: 192.168.1.20
    
    loadbalancers:
      hosts:
        lb01.example.com:
          ansible_host: 192.168.1.30

  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: ~/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3